apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-deploy
  labels:
    app: my-web-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: my-web-app
          image: my-web-app:0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: my-web-app-cm-default
                optional: true
            - configMapRef:
                name: my-web-app-cm-operator
                optional: true