apiVersion: v1
kind: Service
metadata:
  name: my-web-app-svc
  labels:
    app: my-web-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
      protocol: TCP
      name: http
  selector:
    app: my-web-app